baseURL = "https://poker.zobrak.net/"
languageCode = "fr-fr"
title = "ZobraK Poker"
enableRobotsTXT = true
theme = ""

[taxonomies]
  tag = "tags"
  limit = "limits"
  room = "rooms"
  position = "positions"
  action = "actions"
  street = "streets"
  format = "formats"

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true
